In [29]:
import pandas as pd

anthropic_df = pd.read_csv("anthropicfinal.csv")

print(anthropic_df.columns)
anthropic_df.head(5)

Index(['ID', 'Starting URL', 'Category', 'Difficulty', 'Task', 'Anthropic_ID',
       'Anthropic_Status', 'Anthropic_Output', 'Anthropic_Link',
       'Anthropic_Eval', 'AnthropicEvalReason'],
      dtype='object')

,ID,Starting URL,Category,Difficulty,Task,Anthropic_ID,Anthropic_Status,Anthropic_Output,Anthropic_Link,Anthropic_Eval,AnthropicEvalReason
0,0,https://www.acehardware.com,READ,easy,"On the product details page for the ""Black & D...",tsk_388496102632196726,completed,"{""product_name"": ""Black+Decker 20V MAX 3/8 in....",https://app.skyvern.com/tasks/tsk_388496102632...,Success,The bot successfully completed the task
1,1,https://www.acehardware.com,READ,hard,Visit the store locator page to find out which...,tsk_388562620070126340,completed,"{""stores"": [{""name"": ""Golden Valley Ace Hardwa...",https://app.skyvern.com/tasks/tsk_388562620070...,Failure,The bot failed to gather information if the st...
2,2,https://www.acehardware.com,READ,easy,"Search for ""LED light bulbs"" on AceHardware.co...",tsk_388562611480191736,completed,"{""products"": [{""title"": ""Feit Smart Home A19 E...",https://app.skyvern.com/tasks/tsk_388562611480...,Success,The bot successfully completed the task
3,5,https://www.agoda.com,DELETE,hard,"Log in to your Agoda account, add a hotel from...",tsk_390376224296462902,failed,NaN,https://app.skyvern.com/tasks/tsk_390376224296...,Failure,AI agent runs out of steps due to lots of time...
4,7,https://www.agoda.com,READ,easy,"Search for hotels in London, UK that offer fre...",tsk_388562622588385668,completed,"{""hotels"": [{""name"": ""W London"", ""address"": ""W...",https://app.skyvern.com/tasks/tsk_388562622588...,Success,The bot successfully completed the task

In [30]:
browseruser_df = pd.read_csv("browserusefinal.csv")

# print(browseruser_df.columns)

browseruser_df = browseruser_df.drop("Task_BrowserUseCloudFinal", axis=1)
print(len(browseruser_df))
browseruser_df.head(5)

658

,ID,Starting URL,Category,Difficulty,Task,BU_ID,BUOutput,BUCloudLink,BUEval,BUReasoning
0,0,https://www.acehardware.com,READ,easy,"On the product details page for the ""Black & D...",68d17a73-8240-4b47-bb52-8de5d901c422,Repeated efforts to access the Black & Decker ...,https://cloud.browser-use.com/agent/68d17a73-8...,Failure,The user successfully typed in 'Black & Decker...
1,1,https://www.acehardware.com,READ,hard,Visit the store locator page to find out which...,ac01cc85-c9e4-4346-b7c9-6f7afdd7daa8,The task cannot be completed due to persistent...,https://cloud.browser-use.com/agent/ac01cc85-c...,Failure,The task cannot be completed because ongoing n...
2,2,https://www.acehardware.com,READ,easy,"Search for ""LED light bulbs"" on AceHardware.co...",83e5ca55-1e8b-44f4-b1a1-01c6ed0378d9,NaN,https://cloud.browser-use.com/agent/83e5ca55-1...,Failure,The task cannot be completed because ongoing n...
3,5,https://www.agoda.com,DELETE,hard,"Log in to your Agoda account, add a hotel from...",93d78521-b536-4a26-9359-0043c3ff3cce,NaN,https://cloud.browser-use.com/agent/93d78521-b...,Failure,"no video, not enough info"
4,7,https://www.agoda.com,READ,easy,"Search for hotels in London, UK that offer fre...",9ae1e4d6-5ae3-4f35-9b01-ad5e87130330,Here are the first 3 hotels that offer free Wi...,https://cloud.browser-use.com/agent/9ae1e4d6-5...,Failure,"The user successfully found hotels in London, ..."

In [31]:
convergence_df = pd.read_csv("convergencefinal.csv")

print(convergence_df.columns)
print(len(convergence_df))
convergence_df.head(5)

Index(['ID', 'Starting URL', 'Category', 'Difficulty', 'Task',
       'HITL_Convergence_ID', 'convergence_hitl_eval',
       'convergence_hitl_reasoning', 'convergence_hitl_link'],
      dtype='object')
323

,ID,Starting URL,Category,Difficulty,Task,HITL_Convergence_ID,convergence_hitl_eval,convergence_hitl_reasoning,convergence_hitl_link
0,2,https://www.acehardware.com,READ,easy,"Search for ""LED light bulbs"" on AceHardware.co...",HITL-Convergence-1,Success,Succesfully finds the items after searching,https://www.loom.com/share/7b15c03fbcac47e88de...
1,19,https://www.airbnb.com,DELETE,easy,"Log in to your Airbnb account, save a Guest Fa...",HITL-Convergence-4,Failure,The AI Agent could not open AirBnb due to prox...,https://www.loom.com/share/ae2265ccd64440d9846...
2,20,https://www.airbnb.com,DELETE,hard,"Log in to Airbnb, send a query to a host of a ...",HITL-Convergence-3,Failure,The AI Agent could not open AirBnb due to prox...,https://www.loom.com/share/0a7f91936bf84da3aae...
3,22,https://www.airbnb.com,READ,easy,Browse the “Play” section in Paris and extract...,HITL-Convergence-2,Failure,The AI Agent could not open AirBnb due to prox...,https://www.loom.com/share/e18b25f9453d41b4844...
4,33,https://www.alibaba.com,READ,easy,"Search for ""smartphones"" on Alibaba and note h...",HITL-Convergence-7,Success,Succesfully finds the number of items listed,https://www.loom.com/share/0ad69855d4b94aceac4...

In [32]:
openai_df = pd.read_csv("openaicuafinal.csv")

print(openai_df.columns)
print(len(openai_df))
openai_df.head(5)

Index(['ID', 'Starting URL', 'Category', 'Difficulty', 'Task', 'CUA_Task_ID',
       'CUA_Status', 'CUA_Output', 'CUA_Llink', 'CUAEval', 'CUAEvalReasoning'],
      dtype='object')
2452

,ID,Starting URL,Category,Difficulty,Task,CUA_Task_ID,CUA_Status,CUA_Output,CUA_Llink,CUAEval,CUAEvalReasoning
0,0,https://www.acehardware.com,READ,easy,"On the product details page for the ""Black & D...",tsk_384479014539836976,failed,NaN,https://app.skyvern.com/tasks/tsk_384479014539...,Failure,"The bot failed to extract dimensions, voltage,..."
1,1,https://www.acehardware.com,READ,hard,Visit the store locator page to find out which...,tsk_384479115712570694,failed,NaN,https://app.skyvern.com/tasks/tsk_384479115712...,Failure,The bot failed to go to the website.
2,2,https://www.acehardware.com,READ,easy,"Search for ""LED light bulbs"" on AceHardware.co...",tsk_384479130323948522,completed,"{""products"": [{""title"": ""Feit A19 E26 (Medium)...",https://app.skyvern.com/tasks/tsk_384479130323...,Success,"""The bot successfully searched for the relevan..."
3,5,https://www.agoda.com,DELETE,hard,"Log in to your Agoda account, add a hotel from...",tsk_390680467194949116,failed,NaN,https://app.skyvern.com/tasks/tsk_390680467194...,Failure,"The bot reached the website, however it failed..."
4,7,https://www.agoda.com,READ,easy,"Search for hotels in London, UK that offer fre...",tsk_384481404930139924,completed,"{""hotels"": [{""name"": ""Sofitel London Heathrow ...",https://app.skyvern.com/tasks/tsk_384481404930...,Success,"The bot successfully searched London, UK that..."

In [33]:
operator_df = pd.read_csv("operatorhitlfinal.csv")

print(operator_df.columns)
print(len(operator_df))
operator_df.head(5)

Index(['ID', 'Starting URL', 'Category', 'Difficulty', 'Task',
       'HITL_Operator_ID', 'operator_hitl_eval', 'operator_hitl_reasoning',
       'operator_hitl_link'],
      dtype='object')
323

,ID,Starting URL,Category,Difficulty,Task,HITL_Operator_ID,operator_hitl_eval,operator_hitl_reasoning,operator_hitl_link
0,2,https://www.acehardware.com,READ,easy,"Search for ""LED light bulbs"" on AceHardware.co...",HITL-Operator-1,Success,Navigates and finds correct items via search,https://www.loom.com/share/85352b1277d84363b16...
1,19,https://www.airbnb.com,DELETE,easy,"Log in to your Airbnb account, save a Guest Fa...",HITL-Operator-4,Success,AI Agent successfully selected guest favorite ...,https://www.loom.com/share/d72f7868dc2e4172bbc...
2,20,https://www.airbnb.com,DELETE,hard,"Log in to Airbnb, send a query to a host of a ...",HITL-Operator-3,Failure,AI Agent failed to delete. could not find dele...,https://www.loom.com/share/60832434f452439c8e1...
3,22,https://www.airbnb.com,READ,easy,Browse the “Play” section in Paris and extract...,HITL-Operator-2,Success,Agent succesfully goes and finds options and c...,https://www.loom.com/share/93627d5d5cd543edbc9...
4,33,https://www.alibaba.com,READ,easy,"Search for ""smartphones"" on Alibaba and note h...",HITL-Operator-7,Success,AI Agent successfully locates a number for the...,https://www.loom.com/share/bb3f8b6626124e35a42...

In [34]:
rtr_df = pd.read_csv("rtrvrfinal.csv")

print(rtr_df.columns)
print(len(rtr_df))
rtr_df.head(5)

Index(['ID', 'Starting URL', 'Category', 'Difficulty', 'Task', 'Human Notes',
       'Task Output', 'Task Success', 'Execution Time (s)', 'Human Label'],
      dtype='object')
323

,ID,Starting URL,Category,Difficulty,Task,Human Notes,Task Output,Task Success,Execution Time (s),Human Label
0,2,https://www.acehardware.com,READ,easy,"Search for ""LED light bulbs"" on AceHardware.co...",NaN,"[{""title"":""Feit Plug & Play T12 Cool White 48 ...",successful,21.41,Success
1,19,https://www.airbnb.com,DELETE,easy,"Log in to your Airbnb account, save a Guest Fa...",NaN,"Successfully logged in, saved a Guest Favorite...",Successful,41.51,Success
2,20,https://www.airbnb.com,DELETE,hard,"Log in to Airbnb, send a query to a host of a ...","Was actually succesful, unable to delete messa...",I was unable to delete the message. I tried cl...,Failure,182.38,Failure
3,22,https://www.airbnb.com,READ,easy,Browse the “Play” section in Paris and extract...,NaN,"[{""title"":""Learn to bake the French Croissant""...",Successful,25.87,Success
4,33,https://www.alibaba.com,READ,easy,"Search for ""smartphones"" on Alibaba and note h...",NaN,"60,000+ listings",Successful,20.57,Success

In [35]:
skyvern_df = pd.read_csv("skyvern_browserbase_final.csv")

print(skyvern_df.columns)
print(len(skyvern_df))
skyvern_df.head(5)

Index(['ID', 'Starting URL', 'Category', 'Difficulty', 'Task',
       'Browserbase_ID', 'Browserbase_Status', 'Browserbase_Output',
       'Browserbase_Link', 'Browserbase_SkyvernEval',
       'Browserbase_Eval_Reasoning'],
      dtype='object')
2452

,ID,Starting URL,Category,Difficulty,Task,Browserbase_ID,Browserbase_Status,Browserbase_Output,Browserbase_Link,Browserbase_SkyvernEval,Browserbase_Eval_Reasoning
0,0,https://www.acehardware.com,READ,easy,"On the product details page for the ""Black & D...",tsk_v2_392559164203639658,failed,NaN,https://app.skyvern.com/workflows/wpid_3925591...,Failure,The bot failed to close the interrupting popup...
1,1,https://www.acehardware.com,READ,hard,Visit the store locator page to find out which...,tsk_v2_392566680396408158,failed,NaN,https://app.skyvern.com/workflows/wpid_3925666...,Failure,The bot successfully navigated store locator p...
2,2,https://www.acehardware.com,READ,easy,"Search for ""LED light bulbs"" on AceHardware.co...",tsk_v2_392566985339086234,completed,"[{""title"": ""Feit Smart Home A19 E26 (Medium) S...",https://app.skyvern.com/workflows/wpid_3925669...,Success,The bot successfully completed the task
3,5,https://www.agoda.com,DELETE,hard,"Log in to your Agoda account, add a hotel from...",tsk_v2_392566985339086222,failed,NaN,https://app.skyvern.com/workflows/wpid_3925669...,Failure,"The bot reached the website, however it failed..."
4,7,https://www.agoda.com,READ,easy,"Search for hotels in London, UK that offer fre...",tsk_v2_392566985038048114,completed,"{""hotels"": [{""name"": ""ibis London Heathrow Air...",https://app.skyvern.com/workflows/wpid_3925669...,Success,The bot successfully completed the task

In [36]:
skyvern_two_df = pd.read_csv("skyvern2.0final.csv")

print(skyvern_two_df.columns)
print(len(skyvern_two_df))
skyvern_two_df.head(5)

Index(['ID', 'Starting URL', 'Category', 'Difficulty', 'Task', 'Skyvern2.0_ID',
       'Skyvern2.0_Status', 'Skyvern2.0_output', 'Skyvern2.0_Link',
       'Skyvern2.0Eval', 'Skyvern2.0EvalReasoning'],
      dtype='object')
2452

,ID,Starting URL,Category,Difficulty,Task,Skyvern2.0_ID,Skyvern2.0_Status,Skyvern2.0_output,Skyvern2.0_Link,Skyvern2.0Eval,Skyvern2.0EvalReasoning
0,0,https://www.acehardware.com,READ,easy,"On the product details page for the ""Black & D...",tsk_v2_387032933762807326,failed,NaN,https://app.skyvern.com/workflows/wpid_3870329...,Failure,The bot failed to complete the task as the web...
1,1,https://www.acehardware.com,READ,hard,Visit the store locator page to find out which...,tsk_v2_387034832138352186,failed,NaN,https://app.skyvern.com/workflows/wpid_3870348...,Failure,The bot failed to search for the in store pick...
2,2,https://www.acehardware.com,READ,easy,"Search for ""LED light bulbs"" on AceHardware.co...",tsk_v2_387034835835891608,completed,"{""products"": [{""title"": ""Feit A19 E26 (Medium)...",https://app.skyvern.com/workflows/wpid_3870348...,Success,The bot has completed the task
3,5,https://www.agoda.com,DELETE,hard,"Log in to your Agoda account, add a hotel from...",tsk_v2_391023257568239378,completed,"{""favorites_list_status"": ""Trump International...",https://app.skyvern.com/workflows/wpid_3910232...,Success,The bot successfully completed the task
4,7,https://www.agoda.com,READ,easy,"Search for hotels in London, UK that offer fre...",tsk_v2_387034832138352184,completed,"{""hotels"": [{""name"": ""Holiday Inn Express Lond...",https://app.skyvern.com/workflows/wpid_3870348...,Success,The bot successfully completed the task

In [37]:
anthropic_df.head(10)

,ID,Starting URL,Category,Difficulty,Task,Anthropic_ID,Anthropic_Status,Anthropic_Output,Anthropic_Link,Anthropic_Eval,AnthropicEvalReason
0,0,https://www.acehardware.com,READ,easy,"On the product details page for the ""Black & D...",tsk_388496102632196726,completed,"{""product_name"": ""Black+Decker 20V MAX 3/8 in....",https://app.skyvern.com/tasks/tsk_388496102632...,Success,The bot successfully completed the task
1,1,https://www.acehardware.com,READ,hard,Visit the store locator page to find out which...,tsk_388562620070126340,completed,"{""stores"": [{""name"": ""Golden Valley Ace Hardwa...",https://app.skyvern.com/tasks/tsk_388562620070...,Failure,The bot failed to gather information if the st...
2,2,https://www.acehardware.com,READ,easy,"Search for ""LED light bulbs"" on AceHardware.co...",tsk_388562611480191736,completed,"{""products"": [{""title"": ""Feit Smart Home A19 E...",https://app.skyvern.com/tasks/tsk_388562611480...,Success,The bot successfully completed the task
3,5,https://www.agoda.com,DELETE,hard,"Log in to your Agoda account, add a hotel from...",tsk_390376224296462902,failed,NaN,https://app.skyvern.com/tasks/tsk_390376224296...,Failure,AI agent runs out of steps due to lots of time...
4,7,https://www.agoda.com,READ,easy,"Search for hotels in London, UK that offer fre...",tsk_388562622588385668,completed,"{""hotels"": [{""name"": ""W London"", ""address"": ""W...",https://app.skyvern.com/tasks/tsk_388562622588...,Success,The bot successfully completed the task
5,9,https://www.agoda.com,READ,hard,"Search for hotels in Tokyo, Japan that offer a...",tsk_388562613441489654,completed,"{""hotels"": [{""name"": ""APA Hotel & Resort Nishi...",https://app.skyvern.com/tasks/tsk_388562613441...,Success,The bot successfully completed the task
6,10,https://www.agoda.com,READ,hard,Use the flight search tool to find options fro...,tsk_388562622031424268,completed,"{""economy_class_prices"": [{""airline"": ""LATAM A...",https://app.skyvern.com/tasks/tsk_388562622031...,Failure,"The bot reached the website, however it failed..."
7,11,https://www.agoda.com,READ,easy,"Apply the filter for hotels in Bali, Indonesia...",tsk_388562613998451066,completed,"{""hotels"": [{""name"": ""Hilton Garden Inn Bali N...",https://app.skyvern.com/tasks/tsk_388562613998...,Success,The bot successfully completed the task
8,15,https://www.airbnb.com,CREATE,easy,Log in and send a message to the host of a New...,tsk_390377014870584034,failed,NaN,https://app.skyvern.com/tasks/tsk_390377014870...,Failure,AI agent unable to navigate to necessary secti...
9,16,https://www.airbnb.com,CREATE,hard,"Log in, go to ""Airbnb your home"" in the top ri...",tsk_390378806315408682,failed,NaN,https://app.skyvern.com/tasks/tsk_390378806315...,Failure,AI Agent gets blocked by Google auth verificat...

In [38]:
anthropic_df = pd.read_csv("anthropic.csv")
anthropic_df = anthropic_df.drop("agent", axis=1)
anthropic_df.head(5)

,task_id,site,category,difficulty,task_description,evaluation_result,evaluation_reason,task_link,task_output
0,tsk_388496102632196726,https://www.acehardware.com,READ,easy,"On the product details page for the ""Black & D...",success,The bot successfully completed the task,https://app.skyvern.com/tasks/tsk_388496102632...,"{""product_name"": ""Black+Decker 20V MAX 3/8 in...."
1,tsk_388562620070126340,https://www.acehardware.com,READ,hard,Visit the store locator page to find out which...,failure,The bot failed to gather information if the st...,https://app.skyvern.com/tasks/tsk_388562620070...,"{""stores"": [{""name"": ""Golden Valley Ace Hardwa..."
2,tsk_388562611480191736,https://www.acehardware.com,READ,easy,"Search for ""LED light bulbs"" on AceHardware.co...",success,The bot successfully completed the task,https://app.skyvern.com/tasks/tsk_388562611480...,"{""products"": [{""title"": ""Feit Smart Home A19 E..."
3,tsk_390376224296462902,https://www.agoda.com,DELETE,hard,"Log in to your Agoda account, add a hotel from...",failure,AI agent runs out of steps due to lots of time...,https://app.skyvern.com/tasks/tsk_390376224296...,NaN
4,tsk_388562622588385668,https://www.agoda.com,READ,easy,"Search for hotels in London, UK that offer fre...",success,The bot successfully completed the task,https://app.skyvern.com/tasks/tsk_388562622588...,"{""hotels"": [{""name"": ""W London"", ""address"": ""W..."

In [39]:
anthropic_df = anthropic_df.reset_index(drop=True)
anthropic_df["Row_ID"] = anthropic_df.index
anthropic_df.head(5)

,task_id,site,category,difficulty,task_description,evaluation_result,evaluation_reason,task_link,task_output,Row_ID
0,tsk_388496102632196726,https://www.acehardware.com,READ,easy,"On the product details page for the ""Black & D...",success,The bot successfully completed the task,https://app.skyvern.com/tasks/tsk_388496102632...,"{""product_name"": ""Black+Decker 20V MAX 3/8 in....",0
1,tsk_388562620070126340,https://www.acehardware.com,READ,hard,Visit the store locator page to find out which...,failure,The bot failed to gather information if the st...,https://app.skyvern.com/tasks/tsk_388562620070...,"{""stores"": [{""name"": ""Golden Valley Ace Hardwa...",1
2,tsk_388562611480191736,https://www.acehardware.com,READ,easy,"Search for ""LED light bulbs"" on AceHardware.co...",success,The bot successfully completed the task,https://app.skyvern.com/tasks/tsk_388562611480...,"{""products"": [{""title"": ""Feit Smart Home A19 E...",2
3,tsk_390376224296462902,https://www.agoda.com,DELETE,hard,"Log in to your Agoda account, add a hotel from...",failure,AI agent runs out of steps due to lots of time...,https://app.skyvern.com/tasks/tsk_390376224296...,NaN,3
4,tsk_388562622588385668,https://www.agoda.com,READ,easy,"Search for hotels in London, UK that offer fre...",success,The bot successfully completed the task,https://app.skyvern.com/tasks/tsk_388562622588...,"{""hotels"": [{""name"": ""W London"", ""address"": ""W...",4

In [40]:
cols = ["Row_ID"] + [col for col in anthropic_df.columns if col != "Row_ID"]
anthropic_df = anthropic_df[cols]
anthropic_df

,Row_ID,task_id,site,category,difficulty,task_description,evaluation_result,evaluation_reason,task_link,task_output
0,0,tsk_388496102632196726,https://www.acehardware.com,READ,easy,"On the product details page for the ""Black & D...",success,The bot successfully completed the task,https://app.skyvern.com/tasks/tsk_388496102632...,"{""product_name"": ""Black+Decker 20V MAX 3/8 in...."
1,1,tsk_388562620070126340,https://www.acehardware.com,READ,hard,Visit the store locator page to find out which...,failure,The bot failed to gather information if the st...,https://app.skyvern.com/tasks/tsk_388562620070...,"{""stores"": [{""name"": ""Golden Valley Ace Hardwa..."
2,2,tsk_388562611480191736,https://www.acehardware.com,READ,easy,"Search for ""LED light bulbs"" on AceHardware.co...",success,The bot successfully completed the task,https://app.skyvern.com/tasks/tsk_388562611480...,"{""products"": [{""title"": ""Feit Smart Home A19 E..."
3,3,tsk_390376224296462902,https://www.agoda.com,DELETE,hard,"Log in to your Agoda account, add a hotel from...",failure,AI agent runs out of steps due to lots of time...,https://app.skyvern.com/tasks/tsk_390376224296...,NaN
4,4,tsk_388562622588385668,https://www.agoda.com,READ,easy,"Search for hotels in London, UK that offer fre...",success,The bot successfully completed the task,https://app.skyvern.com/tasks/tsk_388562622588...,"{""hotels"": [{""name"": ""W London"", ""address"": ""W..."
...,...,...,...,...,...,...,...,...,...,...
2447,2447,tsk_389631626272115904,https://www.mayoclinic.org,READ,hard,Compare the typical procedures for different t...,failure,the bot could not navigate enough to locate th...,https://app.skyvern.com/tasks/tsk_389631626272...,NaN
2448,2448,tsk_389631625019307726,https://www.mayoclinic.org,READ,easy,Search for comprehensive information about Typ...,success,The bot has completed the task successfully,https://app.skyvern.com/tasks/tsk_389631625019...,"{""key_points"": [""Type 2 diabetes can cause ser..."
2449,2449,tsk_389631621977148602,https://www.nhs.uk,READ,easy,Search for Amputation and list the reasons it ...,success,The bot has completed the task successfully,https://app.skyvern.com/tasks/tsk_389631621977...,"{""amputation_reasons"": [""Severe infection in t..."
2450,2450,tsk_389631629872885936,https://www.nhs.uk,READ,easy,How does an IUD stop pregnancy?\nOnly use www....,success,The bot has completed the task successfully,https://app.skyvern.com/tasks/tsk_389631629872...,"{""iud_pregnancy_explanation"": ""An IUD (intraut..."
2451,2451,tsk_389631629314275028,https://www.nhs.uk,READ,easy,Calculate the BMI of a 28 year old who is195cm...,success,The bot has completed the task successfully,https://app.skyvern.com/tasks/tsk_389631629314...,"{""bmi_value"": 25, ""bmi_category"": ""overweight""}"

In [41]:
anthropic_df["result_flag"] = anthropic_df["evaluation_result"].map({
    "success": 1,
    "failure": 0
})

In [42]:
category = anthropic_df["category"].unique().tolist()
difficulty = anthropic_df["difficulty"].unique().tolist()
site = anthropic_df["site"].unique().tolist()
result = anthropic_df["result_flag"].unique().tolist()
print(len(site))
print(category, difficulty, result)

452
['READ', 'DELETE', 'CREATE', 'UPDATE', 'FILE_MANIPULATION'] ['easy', 'hard'] [1, 0]

# Site-Level Statistics

In [43]:
site_stats = (
    anthropic_df.groupby("site")["evaluation_result"]
    .value_counts()
    .unstack(fill_value=0)
    .reset_index()
)

# Total tasks and success rate per site
site_stats["total_tasks"] = site_stats.sum(axis=1, numeric_only=True)
site_stats["success_rate"] = (site_stats.get("success", 0) / site_stats["total_tasks"] * 100).round(2)

# Optional: sort by success rate
site_stats = site_stats.sort_values(by="success_rate", ascending=False)

# Preview
site_stats

evaluation_result,site,failure,success,total_tasks,success_rate
184,https://www.gov.uk,0,3,3,100.0
199,https://www.howstuffworks.com,0,3,3,100.0
163,https://www.food.com,0,2,2,100.0
164,https://www.foodandwine.com,0,3,3,100.0
165,https://www.foodnetwork.com,0,3,3,100.0
...,...,...,...,...,...
126,https://www.dailymotion.com/ca,3,0,3,0.0
119,https://www.cosmopolitan.com,3,0,3,0.0
109,https://www.cbsnews.com,3,0,3,0.0
106,https://www.cars.com,3,0,3,0.0
451,https://x.com,18,0,18,0.0

# Category-level and difficulty-level stats

In [44]:
# Category-level success rate
category_stats = anthropic_df.groupby("category")["result_flag"].agg(["count", "sum"])
category_stats["success_rate"] = (category_stats["sum"] / category_stats["count"] * 100).round(2)
category_stats = category_stats.rename(columns={"count": "total_tasks", "sum": "num_successes"})
category_stats.reset_index(inplace=True)

# Difficulty-level success rate
difficulty_stats = anthropic_df.groupby("difficulty")["result_flag"].agg(["count", "sum"])
difficulty_stats["success_rate"] = (difficulty_stats["sum"] / difficulty_stats["count"] * 100).round(2)
difficulty_stats = difficulty_stats.rename(columns={"count": "total_tasks", "sum": "num_successes"})
difficulty_stats.reset_index(inplace=True)

# Preview
# category_stats.head()
difficulty_stats.head()

  difficulty  total_tasks  num_successes  success_rate
0       easy         1936           1339         69.16
1       hard          516            279         54.07

# Failed Tasks

In [45]:
# Only consider failed tasks
fail_reasons = (
    anthropic_df[anthropic_df["result_flag"] == 0]["evaluation_reason"]
    .value_counts()
    .reset_index()
)

fail_reasons.columns = ["reason", "count"]

# Preview
fail_reasons

                                                reason  count
0    The bot reached the website, however it failed...     71
1            The bot failed to reach the given website     59
2    The AI bot failed because repeated prompts blo...     19
3    The bot reached the max retry limit and was no...     15
4    Bot reach the max retry limit and wasnt able t...     13
..                                                 ...    ...
480  Stuck with login process again even when using...      1
481  The bot was unable to find the exact option to...      1
482  The bot used the given credentials and still i...      1
483  Bot could not locate the exact tool even with ...      1
484  the bot could not navigate enough to locate th...      1

[485 rows x 2 columns]

# Saving JSONs

In [46]:
import os

# Create output directory if not exists
os.makedirs("data", exist_ok=True)

# Save raw task list
anthropic_df.to_json("data/tasks.json", orient="records", indent=2)

# Save aggregated stats
site_stats.to_json("data/site_stats.json", orient="records", indent=2)
category_stats.to_json("data/category_stats.json", orient="records", indent=2)
difficulty_stats.to_json("data/difficulty_stats.json", orient="records", indent=2)
fail_reasons.to_json("data/failure_reasons.json", orient="records", indent=2)

# Site Category Matrix

In [47]:
site_category_matrix = (
    anthropic_df.groupby(["site", "category"])["result_flag"]
    .agg(["count", "sum"])
    .reset_index()
)

site_category_matrix["success_rate"] = (
    site_category_matrix["sum"] / site_category_matrix["count"] * 100
).round(2)

site_category_matrix = site_category_matrix.rename(columns={
    "count": "total_tasks",
    "sum": "num_successes"
})

# Optional: sort by success rate
site_category_matrix = site_category_matrix.sort_values(by="success_rate", ascending=False)

# Save
site_category_matrix.to_json("data/site_category_matrix.json", orient="records", indent=2)

In [48]:
site_category_matrix

,site,category,total_tasks,num_successes,success_rate
374,https://www.imdb.com,CREATE,5,5,100.0
209,https://www.cbr.com,UPDATE,2,2,100.0
312,https://www.freepik.com,DELETE,1,1,100.0
575,https://www.si.edu,READ,3,3,100.0
309,https://www.foxnews.com,READ,2,2,100.0
...,...,...,...,...,...
244,https://www.deezer.com/us,UPDATE,3,0,0.0
243,https://www.deezer.com/us,READ,4,0,0.0
242,https://www.deezer.com/us,DELETE,3,0,0.0
241,https://www.deezer.com/us,CREATE,7,0,0.0
748,https://x.com,UPDATE,4,0,0.0

# Most failed sites

In [49]:
# Requires site_stats to include both 'success' and 'failure' columns
site_failures = site_stats.copy()
site_failures["failures"] = site_failures.get("failure", 0)
site_failures = site_failures.sort_values(by="failures", ascending=False)

# Optional: Top 10
top_failed_sites = site_failures.head(10)

# Save
top_failed_sites.to_json("data/top_failed_sites.json", orient="records", indent=2)

In [50]:
site_failures.head(50)

evaluation_result,site,failure,success,total_tasks,success_rate,failures
38,https://open.spotify.com,26,0,26,0.00,26
49,https://stackexchange.com,25,14,39,35.90,25
234,https://www.linkedin.com,25,2,27,7.41,25
22,https://github.com,19,5,24,20.83,19
451,https://x.com,18,0,18,0.00,18
127,https://www.deezer.com/us,17,0,17,0.00,17
123,https://www.crunchbase.com,17,3,20,15.00,17
186,https://www.grubhub.com,15,6,21,28.57,15
178,https://www.glassdoor.com/index.htm,14,2,16,12.50,14
53,https://streeteasy.com,14,13,27,48.15,14
130,https://www.dickssportinggoods.com,13,0,13,0.00,13
124,https://www.crunchyroll.com,13,1,14,7.14,13
225,https://www.khanacademy.org,12,4,16,25.00,12
52,https://store.steampowered.com,12,2,14,14.29,12
48,https://soundcloud.com,11,0,11,0.00,11
342,https://www.sofascore.com,11,0,11,0.00,11
77,https://www.alltrails.com,11,0,11,0.00,11
120,https://www.costco.com,10,5,15,33.33,10
203,https://www.ikea.com,10,5,15,33.33,10
391,https://www.twitch.tv,10,0,10,0.00,10
94,https://www.bing.com,9,10,19,52.63,9
76,https://www.allrecipes.com,8,12,20,60.00,8
1,http://www.barnesandnoble.com,8,4,12,33.33,8
121,https://www.countryliving.com,8,6,14,42.86,8
352,https://www.studocu.com,8,4,12,33.33,8
194,https://www.homedepot.com,7,6,13,46.15,7
285,https://www.nordstrom.com,7,4,11,36.36,7
213,https://www.instacart.com,7,14,21,66.67,7
170,https://www.freepik.com,7,5,12,41.67,7
24,https://hinative.com,7,5,12,41.67,7
430,https://www.wikidata.org/wiki/Wikidata:Main_Page,7,4,11,36.36,7
431,https://www.wikihow.com/Main-Page,7,6,13,46.15,7
11,https://economictimes.indiatimes.com,7,3,10,30.00,7
91,https://www.bestbuy.com,6,7,13,53.85,6
403,https://www.uptodown.com/mac,6,8,14,57.14,6
61,https://us.shein.com/?ref=www&rep=dir&ret=us,6,6,12,50.00,6
282,https://www.nike.com,6,4,10,40.00,6
50,https://stackoverflow.com/questions,6,21,27,77.78,6
70,https://www.airbnb.com,6,5,11,45.45,6
79,https://www.answers.com,6,9,15,60.00,6
19,https://gamerant.com,6,5,11,45.45,6
105,https://www.caranddriver.com,5,4,9,44.44,5
291,https://www.nytimes.com,5,4,9,44.44,5
294,https://www.opentable.com,5,5,10,50.00,5
149,https://www.esquire.com,5,5,10,50.00,5
443,https://www.yellowpages.com,5,5,10,50.00,5
380,https://www.today.com,5,6,11,54.55,5
305,https://www.playstation.com/en-us,5,6,11,54.55,5
235,https://www.livejournal.com,5,10,15,66.67,5
304,https://www.pinterest.com,5,9,14,64.29,5

# Category Difficulty Matrix

In [66]:
cat_diff_matrix = (
    anthropic_df.groupby(["category", "difficulty"])["result_flag"]
    .agg(["count", "sum"])
    .reset_index()
)

cat_diff_matrix["success_rate"] = (
    cat_diff_matrix["sum"] / cat_diff_matrix["count"] * 100
).round(2)

cat_diff_matrix.rename(columns={
    "count": "total_tasks",
    "sum": "num_successes"
}, inplace=True)

cat_diff_matrix.to_json("data/category_difficulty_matrix.json", orient="records", indent=2)

In [67]:
cat_diff_matrix.head(10)

            category difficulty  total_tasks  num_successes  success_rate
0             CREATE       easy          359            148         41.23
1             CREATE       hard          154             66         42.86
2             DELETE       easy           82             24         29.27
3             DELETE       hard           67             29         43.28
4  FILE_MANIPULATION       easy           24             14         58.33
5  FILE_MANIPULATION       hard           13              3         23.08
6               READ       easy         1339           1107         82.67
7               READ       hard          241            167         69.29
8             UPDATE       easy          132             46         34.85
9             UPDATE       hard           41             14         34.15

# Most Failed Categories & Difficulties

In [68]:
# Most failed categories (by failure rate)
category_failure_stats = (
    anthropic_df.groupby("category")["result_flag"]
    .agg(["count", "sum"])
    .reset_index()
)

category_failure_stats["failures"] = category_failure_stats["count"] - category_failure_stats["sum"]
category_failure_stats["failure_rate"] = (
    category_failure_stats["failures"] / category_failure_stats["count"] * 100
).round(2)

most_failed_categories = category_failure_stats.sort_values(by="failure_rate", ascending=False)

most_failed_categories.to_json("data/most_failed_categories.json", orient="records", indent=2)

# Most failed difficulties (by failure rate)
difficulty_failure_stats = (
    anthropic_df.groupby("difficulty")["result_flag"]
    .agg(["count", "sum"])
    .reset_index()
)

difficulty_failure_stats["failures"] = difficulty_failure_stats["count"] - difficulty_failure_stats["sum"]
difficulty_failure_stats["failure_rate"] = (
    difficulty_failure_stats["failures"] / difficulty_failure_stats["count"] * 100
).round(2)

most_failed_difficulties = difficulty_failure_stats.sort_values(by="failure_rate", ascending=False)

most_failed_difficulties.to_json("data/most_failed_difficulties.json", orient="records", indent=2)

In [69]:
most_failed_categories.head(10)

            category  count   sum  failures  failure_rate
4             UPDATE    173    60       113         65.32
1             DELETE    149    53        96         64.43
0             CREATE    513   214       299         58.28
2  FILE_MANIPULATION     37    17        20         54.05
3               READ   1580  1274       306         19.37

In [70]:
most_failed_difficulties.head(2)

  difficulty  count   sum  failures  failure_rate
1       hard    516   279       237         45.93
0       easy   1936  1339       597         30.84

# Top Failure Reasons by Category

In [71]:
fail_patterns = (
    anthropic_df[anthropic_df["result_flag"] == 0]
    .groupby(["category", "evaluation_reason"])
    .size()
    .reset_index(name="count")
    .sort_values(by=["category", "count"], ascending=[True, False])
)

top_failures_by_category = (
    fail_patterns.groupby("category")
    .head(5)
    .reset_index(drop=True)
)

top_failures_by_category.to_json("data/top_failures_by_category.json", orient="records", indent=2)

In [72]:
fail_patterns[fail_patterns["category"] == "UPDATE"].head(10)

    category                                  evaluation_reason  count
511   UPDATE  The bot reached the website, however it failed...     11
494   UPDATE          The bot failed to reach the given website      7
469   UPDATE  Bot reach the max retry limit and wasnt able t...      4
471   UPDATE  The AI bot failed because repeated prompts blo...      4
473   UPDATE  The bot cannot login with the given credential...      4
488   UPDATE  The bot failed to login to the account and mov...      3
489   UPDATE            The bot failed to login to the website]      3
495   UPDATE  The bot failed to reach the serve or open the ...      3
508   UPDATE  The bot reached the max retry limit and was no...      3
521   UPDATE  The bot successfully opened the website but di...      3

In [73]:
site_list = sorted(anthropic_df["site"].dropna().unique().tolist())
category_list = sorted(anthropic_df["category"].dropna().unique().tolist())
difficulty_list = sorted(anthropic_df["difficulty"].dropna().unique().tolist())

import json
with open("data/meta_lists.json", "w") as f:
    json.dump({
        "sites": site_list,
        "categories": category_list,
        "difficulties": difficulty_list
    }, f, indent=2)